spring:
  application:
    name: course-catalog-service
message: Hello from default profile

#---
#spring:
#  config:
#    activate:
#      on-profile: prod

---
spring:
  config:
    activate:
      on-profile: dev
message: Hello from dev profile