spring:
  application:
    name: course-catalog-service
  datasource:
    # H2 in-memory DB
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
    # POSTGRES
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/courses
#    url: jdbc:postgresql://localhost:5432/courses # if using Postgres locally
    username: postgres
    password: postgres
  jpa:
    # H2 in-memory DB
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
    # POSTGRES
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # All
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
message: Hello from default profile

#--- # it has its own file application-prod.yml
#spring:
#  config:
#    activate:
#      on-profile: prod
#message: Hello from prod profile

---
spring:
  config:
    activate:
      on-profile: dev
message: Hello from dev profile